services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - network-4juris

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "30080:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - network-4juris

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "35432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - network-4juris

networks:
  network-4juris:
    driver: bridge
